/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as DashboardBakRouteImport } from './routes/dashboard.bak'
import { Route as QuestionBankBakRouteImport } from './routes/question-bank.bak'
import { Route as StudyPlannerBakRouteImport } from './routes/study-planner.bak'
import { Route as TopicsBakRouteImport } from './routes/topics.bak'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBakRoute = DashboardBakRouteImport.update({
  id: '/dashboard/bak',
  path: '/dashboard/bak',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankBakRoute = QuestionBankBakRouteImport.update({
  id: '/question-bank/bak',
  path: '/question-bank/bak',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPlannerBakRoute = StudyPlannerBakRouteImport.update({
  id: '/study-planner/bak',
  path: '/study-planner/bak',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsBakRoute = TopicsBakRouteImport.update({
  id: '/topics/bak',
  path: '/topics/bak',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/bak': typeof DashboardBakRoute
  '/question-bank/bak': typeof QuestionBankBakRoute
  '/study-planner/bak': typeof StudyPlannerBakRoute
  '/topics/bak': typeof TopicsBakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/bak': typeof DashboardBakRoute
  '/question-bank/bak': typeof QuestionBankBakRoute
  '/study-planner/bak': typeof StudyPlannerBakRoute
  '/topics/bak': typeof TopicsBakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/bak': typeof DashboardBakRoute
  '/question-bank/bak': typeof QuestionBankBakRoute
  '/study-planner/bak': typeof StudyPlannerBakRoute
  '/topics/bak': typeof TopicsBakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/auth/callback'
    | '/auth/login'
    | '/dashboard/bak'
    | '/question-bank/bak'
    | '/study-planner/bak'
    | '/topics/bak'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/auth/callback'
    | '/auth/login'
    | '/dashboard/bak'
    | '/question-bank/bak'
    | '/study-planner/bak'
    | '/topics/bak'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/auth/callback'
    | '/auth/login'
    | '/dashboard/bak'
    | '/question-bank/bak'
    | '/study-planner/bak'
    | '/topics/bak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DashboardBakRoute: typeof DashboardBakRoute
  QuestionBankBakRoute: typeof QuestionBankBakRoute
  StudyPlannerBakRoute: typeof StudyPlannerBakRoute
  TopicsBakRoute: typeof TopicsBakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bak': {
      id: '/dashboard/bak'
      path: '/dashboard/bak'
      fullPath: '/dashboard/bak'
      preLoaderRoute: typeof DashboardBakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank/bak': {
      id: '/question-bank/bak'
      path: '/question-bank/bak'
      fullPath: '/question-bank/bak'
      preLoaderRoute: typeof QuestionBankBakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-planner/bak': {
      id: '/study-planner/bak'
      path: '/study-planner/bak'
      fullPath: '/study-planner/bak'
      preLoaderRoute: typeof StudyPlannerBakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/bak': {
      id: '/topics/bak'
      path: '/topics/bak'
      fullPath: '/topics/bak'
      preLoaderRoute: typeof TopicsBakRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  DashboardBakRoute: DashboardBakRoute,
  QuestionBankBakRoute: QuestionBankBakRoute,
  StudyPlannerBakRoute: StudyPlannerBakRoute,
  TopicsBakRoute: TopicsBakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
